name: Update README with Daily Motivation

on:
  schedule:
    # Run daily at 6:30 PM UTC (12:00 AM IST next day)
    - cron: '30 18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Update README with new motivation
        id: update-readme
        run: |
          echo "::group::Updating README.md with new motivation"
          echo "Current working directory: $(pwd)"
          echo "README.md exists: $(test -f README.md && echo 'Yes' || echo 'No')"
          node .github/scripts/update-motivation.js
          echo "::endgroup::"
        
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes detected in README.md"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in README.md"
            echo "changed=true" >> $GITHUB_OUTPUT
            git diff --color README.md | cat
          fi
          
      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          timestamp=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          git commit -m "🌟 Daily motivation update - ${timestamp}"
          git push origin main
          echo "README.md updated successfully at ${timestamp}"
          
      - name: Log workflow completion
        run: |
          if [[ "${{ steps.check-changes.outputs.changed }}" == "true" ]]; then
            echo "✅ README.md updated and changes pushed to repository"
          else
            echo "ℹ️ No changes needed for README.md"
          fi